#!/bin/bash
#
# A git commit hook that rejects:
#  - perl linter failures
#  - js linter failures
#  - whitespace errors
#  - perl debug line errors
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to ".git/hooks/pre-commit".

## 'git diff --staged' - shows the difference between previous and staged commit
## 'git show :$file'   - shows the contents of staged file

FILES=`git diff --staged --name-only`
for file in $FILES
do
    if [ ! -f $file ]
    then
        continue
    fi

    ################################
    ## PERL TESTS
    ################################

    if [ ${file: -3} == ".pm" ] || [ ${file: -3} == ".pl" ] || [ ${file: -2} == '.t' ]
    then
        ## Make sure it passes perl syntax check
        OUT=`git show :$file | perl -c`
        if [ $? != 0 ]
        then
            echo "REJECT: $file fails syntax check"
            echo $OUT
            exit 1
        fi

        ## Check for Data::Printer
        OUT=`git diff --staged $file | ack "(use Data::Printer|use DDP|\$DB::single)"`
        if [ "$OUT" ]
        then
            echo "REJECT: $file contains Data::Printer"
            exit 1
        fi

        ## perlcritic all perl FILES
        OUT=`git show :$file | perlcritic --quiet`
        if [ "$OUT" ]
        then
            echo "REJECT: $file fails perlcritc"
            echo $OUT
            exit 1
        fi

        ## Continue on to next change (don't run js tests)
        continue
    fi

    ################################
    ## JAVASCRIPTS TESTS
    ################################
    if [ ${file: -3} == ".js" ] 
    then
        OUT=`git show :$file | eslint --stdin`
        if [ "$OUT" ]
        then
            echo "REJECT: $file fails eslint"
            echo $OUT
            exit 1
        fi
    fi
done

################################
## Check for whitespace errors
################################
exec git diff-index --check --cached HEAD --

