#!/bin/bash
#
# A git commit hook that rejects:
#  - perl linter failures
#  - js linter failures
#  - whitespace errors
#  - perl debug line errors
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to ".git/hooks/pre-commit".

FILES=`git diff --staged --name-only`
for file in $FILES
do
    if [ ! -f $file ]
    then
        continue
    fi

    ################################
    ## PERL TESTS
    ################################
    if [ ${file: -3} == ".pm" ]
    then
        ## Check for Data::Printer
        OUT=`git diff --staged $file | ack "(use Data::Printer|use DDP)"`
        if [ "$OUT" ]
        then
            echo "Error: Found Data::Printer in $file"
            exit 1
        fi
    fi

    if [ ${file: -3} == ".pm" ] || [ ${file: -3} == ".pl" ] || [ ${file: -2} == '.t' ]
    then
        ## perlcritic all perl FILES
        OUT=`git show :$file | perlcritic --quiet`
        if [ "$OUT" ]
        then
            echo $file
            echo $OUT
            exit 1
        fi
        continue
    fi

    ################################
    ## JAVASCRIPTS TESTS
    ################################
    if [ ${file: -3} == ".js" ] 
    then
        OUT=`git show :$file | eslint --stdin`
        if [ "$OUT" ]
        then
            echo $file
            echo $OUT
            exit 1
        fi
    fi
done

################################
## Check for whitespace errors
################################
exec git diff-index --check --cached HEAD --

